FROM python:3.10.2-slim

ENV PYTHONDONTWRITEBYTECODE=1


RUN apt update && apt install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*
RUN pip install pandas scikit-learn scipy numpy matplotlib jupyterlab

RUN adduser --disabled-login python-user
USER python-user
WORKDIR /home/python-user

CMD ["jupyter-lab", "--ip=0.0.0.0", "--port=80", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.password=''"]

EXPOSE 80

# docker run -d -p 80:80 cdpython
